var _multiplier = 1.0

global.movement_data[ENTITY.PLAYER, MOVE.GROUND_ACCEL]		= 2.000 * _multiplier;
global.movement_data[ENTITY.PLAYER, MOVE.GROUND_FRIC]		= 0.500 * _multiplier;
global.movement_data[ENTITY.PLAYER, MOVE.AIR_ACCEL]			= 0.500 * _multiplier;
global.movement_data[ENTITY.PLAYER, MOVE.AIR_FRIC]			= 0.300 * _multiplier;
global.movement_data[ENTITY.PLAYER, MOVE.WATER_ACCEL]		= 0.500 * _multiplier;
global.movement_data[ENTITY.PLAYER, MOVE.WATER_FRIC]		= 0.100 * _multiplier;
global.movement_data[ENTITY.PLAYER, MOVE.VX_MAX]			= 6.000 * _multiplier;
global.movement_data[ENTITY.PLAYER, MOVE.VY_MAX]			= 20.00 * _multiplier;
global.movement_data[ENTITY.PLAYER, MOVE.VX_MAX_WATER]		= 4.000 * _multiplier;
global.movement_data[ENTITY.PLAYER, MOVE.VY_MAX_WATER]		= 1.000 * _multiplier;
global.movement_data[ENTITY.PLAYER, MOVE.VY_MAX_LADDER]		= 4.000 * _multiplier;
global.movement_data[ENTITY.PLAYER, MOVE.GRAV_NORM]			= 0.900 * _multiplier;
global.movement_data[ENTITY.PLAYER, MOVE.GRAV_SLIDE]		= 0.150 * _multiplier;
global.movement_data[ENTITY.PLAYER, MOVE.GRAV_WATER]		= 0.200 * _multiplier;
global.movement_data[ENTITY.PLAYER, MOVE.JUMP_THRUST]		= 12.00 * _multiplier;
global.movement_data[ENTITY.PLAYER, MOVE.JUMP_HEIGHT]		= 30.00 * _multiplier;
global.movement_data[ENTITY.PLAYER, MOVE.JUMP_HEIGHT_WATER]	= 4.000 * _multiplier;